server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_cms
    username: postgres
    password: 1kitubica
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  main:
    web-application-type: servlet

